title: Monoista
logo: /assets/img/logo.png
description:
show_downloads: false
show_navigation: true
show_footer: false
google_analytics:
theme: jekyll-theme-minimal
plugins: [jekyll-paginate]
paginate: 5
